mitodl/cookiecutter-djangoapp

- README.rst
- cookiecutter.json
- {{ cookiecutter.app_name }}/Dockerfile
- {{ cookiecutter.app_name }}/LICENSE
- {{ cookiecutter.app_name }}/Procfile
- {{ cookiecutter.app_name }}/README.rst
- {{ cookiecutter.app_name }}/apt.txt
- {{ cookiecutter.app_name }}/docker-compose.yml
- {{ cookiecutter.app_name }}/manage.py
- {{ cookiecutter.app_name }}/pylintrc
- {{ cookiecutter.app_name }}/pytest.ini
- {{ cookiecutter.app_name }}/requirements.txt
- {{ cookiecutter.app_name }}/setup.py
- {{ cookiecutter.app_name }}/test_requirements.txt
- {{ cookiecutter.app_name }}/tests/test_settings.py
- {{ cookiecutter.app_name }}/tox.ini
- {{ cookiecutter.app_name }}/uwsgi.ini
- {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/__init__.py
- {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/models.py
- {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/templates/base.html
- {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/templates/{{ cookiecutter.app_name }}/index.html
- {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/tests/test_module.py
- {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/tests/test_views.py
- {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/urls.py
- {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/views.py
- {{ cookiecutter.app_name }}/{{ cookiecutter.project_name }}/settings.py
- {{ cookiecutter.app_name }}/{{ cookiecutter.project_name }}/urls.py
- {{ cookiecutter.app_name }}/{{ cookiecutter.project_name }}/wsgi.py
> Create initial structure

- {{ cookiecutter.app_name }}/Dockerfile
- {{ cookiecutter.app_name }}/apt.txt
- {{ cookiecutter.app_name }}/docker-compose.yml
- {{ cookiecutter.app_name }}/package.json
- {{ cookiecutter.app_name }}/static/.gitignore
- {{ cookiecutter.app_name }}/tox.ini
> Added node to cookiecutter template

- {{ cookiecutter.app_name }}/.coveragerc
- {{ cookiecutter.app_name }}/pytest.ini
Before, the settings didn't pick up coverage for multiple apps. Now it does. Mostly pulled from ccxcon.
> Multi app coverage

- {{ cookiecutter.project_name }}/pylintrc
> Removed reference to six

- {{ cookiecutter.project_name }}/requirements.txt
- {{ cookiecutter.project_name }}/{{ cookiecutter.app_name }}/urls.py
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/settings.py
> Added django-server-status

- {{ cookiecutter.project_name }}/pylintrc
- {{ cookiecutter.project_name }}/test_requirements.txt
> Added django specific pylint

- {{ cookiecutter.project_name }}/static/js/root.js
- {{ cookiecutter.project_name }}/{{ cookiecutter.app_name }}/views.py
> Added __webpack_public_path__

- {{ cookiecutter.project_name }}/.dockerignore
> Added .dockerignore

- {{ cookiecutter.project_name }}/.coveragerc
Increases the precision of coverage reports from 0 to 2 (86% => 86.76%).
> Increased coverage precision to 2

- {{ cookiecutter.project_name }}/docker-compose.yml
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/templates/index.html
Removes some unintentionally added environment variables
> Remove unused environment variables

- {{ cookiecutter.project_name }}/bin/build_heroku_pipeline.sh
In order to make it easier and more repeatable to create a Heroku
environment I wrote a script that uses the Heroku toolbelt and the
`jq` command line utility to provision a pipeline with associated apps.
> Added a script to build a Heroku pipeline based on app.json

- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/templates/base.html
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/views_test.py
Adds missing common bundle. See also https://github.com/mitodl/open-discussions/pull/72 and https://github.com/mitodl/odl-video-service/pull/84
> Add missing common bundle

- {{ cookiecutter.project_name }}/webpack.config.dev.js
Fixes development environments to provide a common bundle when it's referenced
> Add commons chunk for dev

- {{ cookiecutter.project_name }}/app.json
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/envs.py
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/envs_test.py
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/settings.py
See https://github.com/mitodl/open-discussions/pull/88
> Updated app.json and settings.py

- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/settings.py
Related to https://github.com/mitodl/micromasters/pull/3591 and https://github.com/mitodl/micromasters/pull/3615
> Fix logging configuration

- {{ cookiecutter.project_name }}/package.json
- {{ cookiecutter.project_name }}/webpack.config.dev.js
- {{ cookiecutter.project_name }}/webpack.config.prod.js
- {{ cookiecutter.project_name }}/webpack.config.shared.js
> Use ExtractTextPlugin to split off CSS for production

- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/celery.py
https://github.com/mitodl/micromasters/pull/3674
> Don't reference INSTALLED_APPS directly

- {{ cookiecutter.project_name }}/travis/update-docker-hub.sh
> Update local docker files when uploading new docker images

- {{ cookiecutter.project_name }}/.flowconfig
- {{ cookiecutter.project_name }}/flow-typed/npm/lodash_v4.x.x.js
- {{ cookiecutter.project_name }}/flow-typed/npm/react-router_v4.x.x.js
- {{ cookiecutter.project_name }}/flow-typed/npm/redux-asserts_v0.x.x.js
- {{ cookiecutter.project_name }}/flow-typed/npm/redux_v3.x.x.js
- {{ cookiecutter.project_name }}/package.json
- {{ cookiecutter.project_name }}/static/js/containers/App.js
- {{ cookiecutter.project_name }}/static/js/containers/CheckboxPage.js
- {{ cookiecutter.project_name }}/static/js/flow/reduxTypes.js
- {{ cookiecutter.project_name }}/static/js/util/withTracker.js
> Switch to flow-typed

- {{ cookiecutter.project_name }}/codecov.yml
See https://github.com/mitodl/micromasters/pull/3811
> Turn off code coverage status checks to prevent blocking deployment

- {{ cookiecutter.project_name }}/Procfile
- {{ cookiecutter.project_name }}/docker-compose.yml
Fixes #126 
The only way to really test this is to create a new project and repo on github and run the tests on travis, so I'd just suggest looking at the other two PRs in other projects that fixed this:
mitodl/micromasters#3879
mitodl/open-discussions#335
> Fixed travis error output

- {{ cookiecutter.project_name }}/Dockerfile
- {{ cookiecutter.project_name }}/static/js/lib/api.js
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/settings.py
https://github.com/mitodl/open-discussions/pull/813
> Add sentry handler to logger

- {{ cookiecutter.project_name }}/Dockerfile
- {{ cookiecutter.project_name }}/requirements.in
- {{ cookiecutter.project_name }}/static/js/lib/api.js
- {{ cookiecutter.project_name }}/static/js/lib/sanctuary.js
Closes #137 
Also updates python, celery version (its docker instance no longer started correctly on the previous version) and fixes several JS lint issues.
> Update django and celery versions

- {{ cookiecutter.project_name }}/scripts/envs.sh
- {{ cookiecutter.project_name }}/webpack_dev_server.sh
> Remove IS_OSX from envs.sh

- {{ cookiecutter.project_name }}/package.json
- {{ cookiecutter.project_name }}/static/js/entry/root.js
- {{ cookiecutter.project_name }}/static/js/flow/declarations.js
- {{ cookiecutter.project_name }}/travis/js_tests.sh
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/templates/base.html
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/views.py
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/views_test.py
> Add support for Raven

- {{ cookiecutter.project_name }}/Aptfile
- {{ cookiecutter.project_name }}/app.json
> Added Aptfile support for heroku

- {{ cookiecutter.project_name }}/LICENSE
- {{ cookiecutter.project_name }}/scripts/test/no_auto_migrations.sh
Remove an exception which doesn't apply to future projects, and update the copyright year in our LICENSE
> Forbid all auto migrations

- {{ cookiecutter.project_name }}/Dockerfile
- {{ cookiecutter.project_name }}/Dockerfile-node
- {{ cookiecutter.project_name }}/package.json
- {{ cookiecutter.project_name }}/pylintrc
- {{ cookiecutter.project_name }}/requirements.in
- {{ cookiecutter.project_name }}/runtime.txt
- {{ cookiecutter.project_name }}/test_requirements.txt
- {{ cookiecutter.project_name }}/travis/Dockerfile-travis-watch-build
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/middleware.py
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/templatetags/render_bundle.py
Upgrades the docker python version to stretch so the project can actually be built when first generated.
Tests should pass
> Update to stretch

- {{ cookiecutter.project_name }}/Procfile
Adds newrelic and pgbouncer to worker processes similar to the config on the other apps that we're running in Heroku.
> Added newrelic and pgbouncer to worker processes

- {{ cookiecutter.project_name }}/app.base.json
- {{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}/settings.py
> Remove MAILGUN_BCC_TO_EMAIL

- {{ cookiecutter.project_name }}/app.base.json
> Move apt buildpack to the start of app.base.json

- {{ cookiecutter.project_name }}/.pre-commit-config.yaml
- {{ cookiecutter.project_name }}/.secrets.baseline
- {{ cookiecutter.project_name }}/README.md
> Add pre-commit configuration

- {{ cookiecutter.project_name }}/Dockerfile-nb
- {{ cookiecutter.project_name }}/README.md
- {{ cookiecutter.project_name }}/docker-compose-notebook.yml
- {{ cookiecutter.project_name }}/localdev/app.ipynb.example
> Add docker notebook configuration
